# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2

updates:
  # GitHub Actions:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - infrastructure
  # Maven plugins:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-patch-days: 14
      include: [ "*" ]
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - infrastructure
    registries: "*"
    groups:
      maven-wrapper:
        patterns:
          - "org.apache.maven.wrapper:maven-wrapper"
          - "org.apache.maven:apache-maven"
    allow:
      - dependency-name: "com.diffplug.spotless:spotless-maven-plugin"
      - dependency-name: "org.apache.maven.plugins:*"
      - dependency-name: "org.codehaus.mojo:*"
      - dependency-name: "org.sonatype.central:central-publishing-maven-plugin"
