/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_givimad_piperjni_PiperJNI */

#ifndef _Included_io_github_givimad_piperjni_PiperJNI
#define _Included_io_github_givimad_piperjni_PiperJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    newConfig
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_piperjni_PiperJNI_newConfig
  (JNIEnv *, jobject);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    freeConfig
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_givimad_piperjni_PiperJNI_freeConfig
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    setESpeakDataPath
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_givimad_piperjni_PiperJNI_setESpeakDataPath
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    setTashkeelModelPath
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_givimad_piperjni_PiperJNI_setTashkeelModelPath
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    initializeConfig
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_givimad_piperjni_PiperJNI_initializeConfig
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    terminateConfig
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_givimad_piperjni_PiperJNI_terminateConfig
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    loadVoice
 * Signature: (ILjava/lang/String;Ljava/lang/String;JZ)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_piperjni_PiperJNI_loadVoice
  (JNIEnv *, jobject, jint, jstring, jstring, jlong, jboolean);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    freeVoice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_givimad_piperjni_PiperJNI_freeVoice
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    voiceUsesESpeakPhonemes
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_givimad_piperjni_PiperJNI_voiceUsesESpeakPhonemes
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    voiceUsesTashkeelModel
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_givimad_piperjni_PiperJNI_voiceUsesTashkeelModel
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    voiceSampleRate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_github_givimad_piperjni_PiperJNI_voiceSampleRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    textToAudio
 * Signature: (IILjava/lang/String;Lio/github/givimad/piperjni/PiperJNI/AudioCallback;)[S
 */
JNIEXPORT jshortArray JNICALL Java_io_github_givimad_piperjni_PiperJNI_textToAudio
  (JNIEnv *, jobject, jint, jint, jstring, jobject);

/*
 * Class:     io_github_givimad_piperjni_PiperJNI
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_givimad_piperjni_PiperJNI_getVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
