/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_jvoiceproject_piperjni_PiperJNI */

#ifndef _Included_io_github_jvoiceproject_piperjni_PiperJNI
#define _Included_io_github_jvoiceproject_piperjni_PiperJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_jvoiceproject_piperjni_PiperJNI
 * Method:    loadVoice
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jvoiceproject_piperjni_PiperJNI_loadVoice
  (JNIEnv *, jobject, jstring, jstring, jstring, jlong);

/*
 * Class:     io_github_jvoiceproject_piperjni_PiperJNI
 * Method:    freeVoice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_jvoiceproject_piperjni_PiperJNI_freeVoice
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_jvoiceproject_piperjni_PiperJNI
 * Method:    voiceUsesESpeakPhonemes
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_jvoiceproject_piperjni_PiperJNI_voiceUsesESpeakPhonemes
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_jvoiceproject_piperjni_PiperJNI
 * Method:    voiceSampleRate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_github_jvoiceproject_piperjni_PiperJNI_voiceSampleRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_jvoiceproject_piperjni_PiperJNI
 * Method:    textToAudio
 * Signature: (ILjava/lang/String;Lio/github/jvoiceproject/piperjni/PiperJNI/AudioCallback;)[S
 */
JNIEXPORT jshortArray JNICALL Java_io_github_jvoiceproject_piperjni_PiperJNI_textToAudio
  (JNIEnv *, jobject, jint, jstring, jobject);

/*
 * Class:     io_github_jvoiceproject_piperjni_PiperJNI
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_jvoiceproject_piperjni_PiperJNI_getVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
